/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
    const Product = sequelize.define('Product', {
        code: {
            type: DataTypes.STRING(100),
            autoIncrement: false,
            primaryKey: true,
            allowNull: false,
            unique: true,
        },
        name: {
            type: DataTypes.STRING(1000),
            allowNull: false,
            defaultValue: ""
        },
        brands: {
            type: DataTypes.STRING(1000),
            allowNull: false,
            defaultValue: ""
        },
        categorias: DataTypes.STRING(1000),
        categoria_principal: {
            type: DataTypes.STRING(1000),
            allowNull: true,
            defaultValue: ""
        },
        product_preview: {
            type: DataTypes.STRING(254),
            allowNull: true,
            defaultValue: true
        },
        ingredients_preivew: {
            type: DataTypes.STRING(254),
            allowNull: true,
            defaultValue: true
        },
        nutrition_preview: {
            type: DataTypes.STRING(254),
            allowNull: true,
            defaultValue: true
        },
    }, {
        tableName: 'Product',
        timestamps: false,
        underscored: false,

        classMethods: {
            associate: function associate(models) {
            }
        },
    });

    return Product;
};
